### ISSUE TITLE
Transitions not getting oldView/newView as arguments

### ISSUE THREAD

**Issue by lightblade** [ef4/liquid-fire#221]
http://ef4.github.io/liquid-fire/#/transitions/defining

The doc says transitions gets oldView/newView as argument, but I'm not seeing this being passed in.

https://github.com/ef4/liquid-fire/blob/master/app/transitions/move-over.js

Is the doc wrong?

**Comment by ef4** [comment]
The doc is correct for the latest liquid-fire release, but not for master. There are undocumented changes on master, which is why it hasn't been released yet.

I have simplified this API so that instead of receiving oldView and a function that inserts and returns a promise for newView, you have direct access to `this.oldElement`, `this.newElement`, plus a bunch of other related state.

The built-in transitions illustrate this new style, and the available fields come from here in the source: https://github.com/ef4/liquid-fire/blob/14752e71d3685c3890a1a9642cbc7c3818567b70/addon/running-transition.js#L42-L79

**Comment by lightblade** [comment]
Ah ok, good to know.

Thanks!
