### ISSUE TITLE
Add something about reverse() to docs

### ISSUE THREAD

**Issue by drewbaker** [ef4/liquid-fire#223]
Hey Guys,

Just started using LF, and can't find anything about what reverse actually does?

First thing I did was go left-to-right between everything, but expect this to go right-to-left when pressing back button or going back to to the page we just came from. That was my expectation with reverse(). Am I wrong?

```
	// Everything use left or right
	this.transition(
		this.use('toLeft'),
		this.reverse('toRight')
	);
```

**Comment by ef4** [comment]
`reverse` is not about "going back". It can't be, since every route in your app has it's own URL, meaning users can start *anywhere*, so what's normally "forward" might become "back" and vice versa, depending on where somebody starts.

Instead, `reverse` says what happens if the current rule matches with all its "from" constraints swapped with its "to" constraints. Your rule has no constraints, so it will always match anyway, and reverse won't have any effect. 

Instead of writing two verbose rules like this:

```js
this.transition(
  this.fromRoute('master'),
  this.toRoute('detail'),
  this.use('toLeft'),
);
this.transition(
  this.fromRoute('detail'),
  this.toRoute('master'),
  this.use('toRight'),
);
```

`reverse` lets you combine them into:

```js
this.transition(
  this.fromRoute('master'),
  this.toRoute('detail'),
  this.use('toLeft'),
  this.reverse('toRight')
);
```


It's documented here: http://ef4.github.io/liquid-fire/#/transition-map/choosing-transitions

**Comment by drewbaker** [comment]
OK this makes sense. So there really isn't a way to do a blanket rule that has reverse for all routes? You'd have define it for every route (which could be a lot of routes)?

**Comment by ef4** [comment]
If you mean a rule that does something different based on whether the user hit the back button, then no. But I think that's not a good idea anyway. It can lead to very confusing app behavior for users.

Your original example:

```js
 // Everything use left or right
    this.transition(
        this.use('toLeft'),
        this.reverse('toRight')
    );
```

Doesn't make sense because if *everything* goes left, then nothing ever goes right. You need to pick which ones go which way. For example, maybe you have a "home" route, and everything else goes left from there:

```js
    this.transition(
        this.fromRoute("home"),
        this.use('toLeft'),
        this.reverse('toRight')
    );
```

If you really can't pick, then use transitions that are not directional, like "fade" instead of "toLeft".

**Comment by drewbaker** [comment]
I was hoping it might be possible to keep track of where a user had come from, and that went right, otherwise everything went left.

Something like:

```
if( request_route == referral_route ) {
    this.use('toRight'),
} else {
    this.use('toLeft'),
}
```

**Comment by ef4** [comment]
You could potentially write your own history service that tracks the user and then query the history service in a fromRoute rule. But I think it's really hard to not deliver confusing user experience that way.

The value in having views "move" side to side is not that it looks cool -- it's that it lets the user build a map in their mind of how the views relate to each other. If you change that map on them depending on their history, it makes your app harder to understand than it would be with no animations at all.

**Comment by drewbaker** [comment]
` lets the user build a map in their mind of how the views relate to each other.`

Never thought of it like that, great point!
