### ISSUE TITLE
[TESTING] What is the best way to test a component that contains a liquid-fire if helper?

### ISSUE THREAD

**Issue by kiwiupover** [ef4/liquid-fire#240]
Here is a test that worked well with version `0.17.0` Can I see an example I could follow to update this test to work going forward. This really about get the right dependancies setup.

```js

import {
  describeComponent,
  it
} from 'ember-mocha';

import { initialize } from 'liquid-fire';

describeComponent(
  'data-card',
  'DataCardComponent',
  {
    needs: ['helper:liquid-if', 'view:liquid-if',
            'view:liquid-if', 'helper:liquid-with',
            'view:liquid-with', 'view:liquid-child',
            'template:liquid-with', 'helper:with-apply']
  },
  function() {
    it('renders', function() {
      // creates the component instance
      initialize(this.container);

      var component = this.subject();
      expect(component._state).to.equal('preRender');

      // renders the component on the page
      this.render();
      expect(component._state).to.equal('inDOM');
    });
  }
);

```

**Comment by ef4** [comment]
The core problem is that this isn't really a unit test. It depends on many, many other modules. 

And that's ok. I think the right way to test components is with integration tests -- but more tightly scoped integration tests than what the current ember docs describe, which are really whole-app acceptance tests.

We have been adding some features to ember-test-helpers that make this easier. There is now an "integration:true" option that you can pass instead of "needs" that will make all the modules available. I don't know offhand what version of ember-test-helpers it released in.

I'm also working on new kind of test module that lets you test directly with a template snippet. The underlying infrastructure is available in ember-test-helpers, but it isn't exposed through ember-mocha yet. I'm using the code directly in liquid-fire, and you can do the same thing if you want to. See for example: https://github.com/ef4/liquid-fire/blob/master/tests/integration/helpers/liquid-if-test.js

**Comment by kiwiupover** [comment]
You are right this is not really an unit test. I will follow your lead with the integration test method.

Cheers for all your hard work @ef4
