### ISSUE TITLE
liquid-if truth/falsy class name attributes

### ISSUE THREAD

**Issue by knownasilya** [ef4/liquid-fire#242]
Would be nice to have these.

```js
{{#liquid-if isLoading class='loading' truthyClass='still-loading' falsyClass='not-loading'}}
{{/liquid-if}}
```

This would help with animating absolute positioned elements.

**Comment by ef4** [comment]
I don't think we want specialized properties, we should just make sure the general-purpose htmlbars stuff works. Some of the syntax is still being improved, but you can already do this:

```handlebars
{{#liquid-if isLoading class=(if isLoading "loading still-loading" "loading not-loading")}}
{{/liquid-if}}
```

What do you mean by "help with animating absolute positioned elements?". Because if you mean you want to use different animations depending on this class, it's easier to just write the transition rules to match `toValue(true)` vs `toValue(false)`.

**Comment by knownasilya** [comment]
@ef4 that's a good solution. Thanks.

The liquid-if element overlaps other elements while they load (a map), and once they load the liquid-if element needs to be resized/zindexed so the map below can be accessed.
