### ISSUE TITLE
strategy for transitioning from route1.index to route2.index and loading substate

### ISSUE THREAD

**Issue by Eptis** [ef4/liquid-fire#301]
Hey I might have an edge case, but what I want to do is animate in a carousel with `toLeft` and `toRight` between certain routes depending on the current `route` and the one that is to the left or right of it. Basically I have three routes(in order): `general-info`, `items` and `history`. When transitioning from `general-info` to `items` I want to use `toLeft` and `toRight` in reverse. This works perfectly unless you have a loading substate, which brakes the transition because liquid fire only receives that last two routes which resolved in a transition. It basically animates from `items.loading` to `items`. 
Is there any way to do this? Maybe find out which route was transitioned from before `items.loading`.

**Comment by nurazem** [comment]
@Eptis Did you find a solution for this issue?

**Comment by Eptis** [comment]
No not yet, still thinking about it. One think might be to use explode and include data-transition-id's in the dom.

**Comment by richmolj** [comment]
I have this same situation, I'm considering

* Removing all loading routes
* Replace with a loading component like

```handlebars
{{#loading-area model.isPending as |currentModel|}}
  <!-- dom -->
{{/loading-area}}
```
* Make all models return a hash instead of a promise so the component immediately renders

I dislike this though, since it goes against ember conventions and means nested routes that shouldn't fire `model` until the parent resolves will require more work.
