### ISSUE TITLE
Error When Testing

### ISSUE THREAD

**Issue by tomoguisuru** [ef4/liquid-fire#337]
When running unit tests on components I'm getting the following error when using the bool set on the component
`Error: Assertion Failed: You can only pass attributes (such as name=value) not bare values to a helper for a View found in '(subclass of Ember.Component)'`

This is what my implementation looks like:
`{{#liquid-if isOpen class="liquid--fade"}}
blah blah
{{/liquid-if}}`

Removing isOpen resolves the test error

**Comment by ef4** [comment]
What ember and liquid-fire versions?

Is it really a unit test, or a component integration test?

**Comment by tomoguisuru** [comment]
Sorry for the late response, we're using ember-cli@0.2.7 and liquid-fire@0.19.4.

here is the code for the component test that we're using liquid-if in (basically generated code with the addition of the needs: ['component:liquid-id']

```
moduleForComponent 'settings-info', 'Unit | Component | Settings Info', {
  # Specify the other units that are required for this test
  needs: ['component:liquid-if']
}

test('it renders', (assert) ->
  assert.expect 2

  # Creates the component instance
  component = @subject()
  assert.equal(component._state, 'preRender')

  # Renders the component to the page
  @render()
  assert.equal(component._state, 'inDOM')
)
```

**Comment by ef4** [comment]
What ember (not ember-cli) version? It prints in the browser console when you app starts, in dev mode.

**Comment by tomoguisuru** [comment]
sorry, I meant to include it, ember@1.12.1

**Comment by turboMaCk** [comment]
I have same issue with `ember@1.12.1` and `liquid-fire@0.19.5`

**Comment by turboMaCk** [comment]
I found solution for this. Just include liquid as both component and helper. In my case:
```
needs: ['component:liquid-with', 'helper:liquid-with']
```
works.

**Comment by ef4** [comment]
That makes sense.

However, I would strongly caution against trying to "unit test" components. You aren't really doing a unit test (if you were, an external library like liquid-fire would not be involved). You're doing an integration test, and Ember has very nice support for component integration tests.

The above example test doesn't even make sense as a test: `_state` is private and meaningless to your application's requirements. I realize that examples like this have historically shipped within ember-cli itself, which is why people are doing this. But I'm trying to get the word out: stop, there is a much better way.

On any recent ember-cli, if you `ember generate component-test settings-info` you will get a nice integration test by default. Start with that, and test externally visible behaviors -- not `_state`.
